import fs from 'node:fs';
import {load} from 'cheerio';
const site='www-lolacosmetics-com-br-b005530a/root-8a5edab2';
const root=`docs/research/${site}`, out=`src/components/sites/${site}`;
const raw=JSON.parse(fs.readFileSync(`${root}/desktop-extraction.json`));
const d=JSON.parse(fs.readFileSync(`${root}/loaded-extraction.json`));
const mobile=JSON.parse(fs.readFileSync(`${root}/mobile-extraction.json`));
const manifest=JSON.parse(fs.readFileSync(`${root}/asset-manifest.json`));
const options=JSON.parse(fs.readFileSync(`${root}/slider-options.json`));
const local=s=>manifest[s]||s;
function rewrite(s){for(const [u,l] of Object.entries(manifest))s=s.split(u).join(l);return s;}
let css='';
for(const sheet of raw.stylesheets){if(sheet.url&&manifest[sheet.url])css+='\n'+fs.readFileSync('public'+manifest[sheet.url],'utf8');else if(sheet.css)css+='\n'+sheet.css;}
css+='\n'+d.inlineStyles.join('\n');
css=rewrite(css).replace(/@import\s+[^;]+;/g,'').replace(/@charset\s+[^;]+;/g,'');
fs.writeFileSync(`public/sites/${site}/source.css`,css);
let sliderIndex=0;
function clean(html){const $=load(html,{},false);$('script,iframe,style,noscript').remove();$('*').each((i,e)=>{for(const k of Object.keys(e.attribs||{})){if(/^on/i.test(k)||['data-bind','data-widget-js','data-messages'].includes(k))$(e).removeAttr(k);}if(e.tagName==='a'){const href=$(e).attr('href');if(href&&href!=='/'&&!href.startsWith('#')&&!/^(https?:|mailto:|tel:)/.test(href))$(e).attr('href',new URL(href,'https://www.lolacosmetics.com.br').href);if(/^javascript:/i.test(href||''))$(e).attr('href','#');}if(e.tagName==='form')$(e).removeAttr('action').removeAttr('method');});
$('.slick-slider').each((i,e)=>{const sl=$(e);const contents=sl.find('> .slick-list > .slick-track > :not(.slick-cloned)').toArray().map(c=>$(c).children().children().toString()).join('');const opt=options[sliderIndex++]?.options||options[2].options;sl.html(contents).removeClass('slick-initialized slick-slider slick-dotted').attr('data-lola-slider',JSON.stringify(opt));sl.find('[tabindex]').removeAttr('tabindex');});
$('img').each((i,e)=>{const image=$(e);const src=image.attr('data-src')||image.attr('src');if(src)image.attr('src',local(src));image.removeAttr('data-src').removeClass('lazyload fade animated');if(!image.attr('alt'))image.attr('alt','Lola Cosmetics');});
$('[style]').each((i,e)=>$(e).attr('style',rewrite($(e).attr('style'))));
return rewrite($.html()).replace(/<!--[^]*?-->/g,'');}
const fragments={};for(const [name,s] of Object.entries(d.sections))fragments[name]=clean(s.html);
const $m=load(mobile.html);fragments.HeaderMobile=clean($m('#header').toString());fragments.HeroMobile=clean($m('.fullbanner').toString());
// Mobile slider options come from the same hero instance: one slide and four dots.
fragments.HeroMobile=fragments.HeroMobile.replace(/data-lola-slider="[^"]*"/g,`data-lola-slider="${JSON.stringify(options[0].options).replaceAll('"','&quot;')}"`);
fs.writeFileSync(`${out}/fragments.json`,JSON.stringify(fragments,null,2));
const shadows=d.shadows.filter(x=>['WIDDE-PRO-HIGHLIGHTS','WIDDE-PRO-CAROUSEL'].includes(x.tag));
fs.writeFileSync(`${out}/media-data.json`,JSON.stringify(shadows.map(x=>({tag:x.tag,html:rewrite(x.html),images:x.images.map(im=>({...im,src:local(im.src),poster:local(im.poster)}))})),null,2));
fs.writeFileSync(`${out}/types.ts`,'export interface LolaProduct { id: string; name: string; image: string; price: number; quantity: number; }\nexport type LolaSectionName = '+Object.keys(fragments).map(k=>JSON.stringify(k)).join(' | ')+';\n');
for(const [name,s] of Object.entries(d.sections)){const text=load(s.html).text().replace(/\s+/g,' ').trim();const st=s.tree.styles;const spec=`# ${name} Specification\n\n## Overview\n- Target: ${out}/${name}.tsx\n- Screenshot: docs/design-references/${site}/desktop-loaded-1440.png and mobile-390.png\n- Interaction: ${['Hero'].includes(name)?'time-driven autoplay 5000ms plus click/swipe, transition 500ms ease': ['Categories','Favorites','DailyDeals','Launches','Collector'].includes(name)?'click/swipe carousel, 500ms ease':'links, hover and local UI controls'}\n\n## DOM Structure\nExact sanitized source markup is provided as fragments.${name} in fragments.json. All source class names and inline SVGs retained. Render as HTML with display:contents wrapper to preserve selectors. Original CSS is loaded globally from local source.css, including all descendant values. Do not approximate or override original styles.\n\n## Computed Styles\n${Object.entries(st).map(([k,v])=>'- '+k+': '+v).join('\n')}\n\n## States & Behaviors\nNative scrolling, fixed header remains 212px at 1440 before and after scroll; no Lenis. Desktop navigation hover reveals menus (block/grid/flex); mobile .dropdown-menu toggles .active-menu with left 0px and 0.3s transition. Hero starts at slide 0, auto advance every 5000ms, pauses on hover/focus, dots clickable. Product carousels: 4 desktop, 3 below 1250, 2 below 1024; paired promo/collector 2 throughout.\n\n## Per-State Content\nAll carousel slide contents retained in fragments; source inline icons retained verbatim. No backend or authentication. Non-home destinations link to original site. Local demo purchase/wishlist are handled separately.\n\n## Assets\nAll URLs in fragment are rewritten using asset-manifest.json to /sites/${site}/. Exact source imagery, fonts, SVGs, and videos locally hosted.\n\n## Text Content (verbatim)\n${text}\n\n## Responsive Behavior\n1440: original desktop layout. 768 and 390: source CSS media queries, header switches at 1100px. Matching mobile screenshot and mobile-specific hero/header fragments available. Product rails use breakpoints above.\n`;
fs.writeFileSync(`${root}/components/${name}.spec.md`,spec);}
fs.writeFileSync(`${root}/PAGE_TOPOLOGY.md`,'# Page topology\n\nFixed Header → Hero → video Stories → Categories → Favorites → HairTypes → video rail → DailyDeals → Launches → Collector → BeforeAfter → Affiliate → Blog → Reviews → Footer. Cookie banner fixed bottom.\n\nNative scroll, no Lenis or scroll-snap. Header stays fixed at top. Carousels click/swipe driven; hero additionally autoplay.\n');
fs.writeFileSync(`${root}/BEHAVIORS.md`,'# Observed behaviors\n\nDesktop header stays fixed, 212px tall at scroll 0 through 7148px. Mobile header 125.25px. Hover on desktop nav reveals block/grid/flex menus. Hamburger opens .dropdown-menu.active-menu, left:0px; transition:0.3s. Header breakpoint 1100px.\n\nHero uses Slick, autoplay 5000ms, speed 500ms ease, dots, swipe, pause on hover/focus, infinite. Categories four slides desktop, two below1024. Product carousels four desktop/three below1250/two below1024. Promo and collector two. Source options saved in slider-options.json.\n\nVideo thumbnails autoplay muted in circular highlights. Click opens video view. Newsletter form and checkout are demo-only; links to unrequested routes use live source. Cookie consent hides banner and persists locally.\n\nThird-party video and review widgets can change dimensions when asynchronous content loads; clone uses captured loaded states.\n');
console.log('Prepared',Object.keys(fragments).length,'fragments, source CSS and specifications');
